"""Immutable research data and snapshot primitives."""

from .canonical import (
    CanonicalJSONError,
    canonical_hash,
    canonical_json,
    canonicalize,
)
from .datasets import DatasetStatus
from .availability import (
    AvailabilityAssessment,
    DATASET_DEFINITIONS,
    DEFAULT_RESEARCH_DATASETS,
    DatasetDefinition,
    assess_dataset_rows,
    to_tushare_ts_code,
)
from .raw_store import RawArtifactReference, RawArtifactStore
from .repositories import (
    DatasetSnapshotInput,
    FactorSnapshotInput,
    LeaseFence,
    ResearchSnapshotInput,
    ResearchSnapshotRepository,
    SnapshotWriteResult,
)
from .collector import (
    DatasetCollectionResult,
    ResearchCollectionResult,
    ResearchDatasetCollector,
)
from .decision_outcome_v2_datasets import (
    CSI300_INDEX_CODE,
    CSI300_INDEX_DAILY_DATASET,
    CSI300_INDEX_NAME,
    DECISION_OUTCOME_V2_BENCHMARK_DATASETS,
    SW1_INDEX_CLASSIFY_DATASET,
    SW1_INDEX_DAILY_DATASET,
    SW1_INDEX_MEMBER_ALL_DATASET,
    DecisionOutcomeV2DatasetQuery,
    Sw1MembershipResolutionV2,
    benchmark_dataset_unavailable_reason,
    build_csi300_index_daily_query,
    build_sw1_index_classify_query,
    build_sw1_index_daily_query,
    build_sw1_index_member_all_query,
    resolve_sw1_membership,
)
from .snapshot_service import (
    FACTOR_ENGINE_VERSION,
    FIELD_DICTIONARY_VERSION,
    SNAPSHOT_VERSION,
    FrozenResearchSnapshot,
    build_research_snapshot,
    model_route_fingerprint,
    persist_research_snapshot,
    project_factors,
    project_model_route,
    project_structured_datasets,
    safe_project_context_pack,
)

__all__ = [
    "CanonicalJSONError",
    "CSI300_INDEX_CODE",
    "CSI300_INDEX_DAILY_DATASET",
    "CSI300_INDEX_NAME",
    "AvailabilityAssessment",
    "DATASET_DEFINITIONS",
    "DECISION_OUTCOME_V2_BENCHMARK_DATASETS",
    "DEFAULT_RESEARCH_DATASETS",
    "DatasetCollectionResult",
    "DatasetDefinition",
    "DatasetSnapshotInput",
    "DatasetStatus",
    "DecisionOutcomeV2DatasetQuery",
    "FactorSnapshotInput",
    "FACTOR_ENGINE_VERSION",
    "FIELD_DICTIONARY_VERSION",
    "FrozenResearchSnapshot",
    "LeaseFence",
    "RawArtifactReference",
    "RawArtifactStore",
    "ResearchSnapshotInput",
    "ResearchCollectionResult",
    "ResearchDatasetCollector",
    "ResearchSnapshotRepository",
    "SW1_INDEX_CLASSIFY_DATASET",
    "SW1_INDEX_DAILY_DATASET",
    "SW1_INDEX_MEMBER_ALL_DATASET",
    "SnapshotWriteResult",
    "Sw1MembershipResolutionV2",
    "SNAPSHOT_VERSION",
    "build_research_snapshot",
    "assess_dataset_rows",
    "benchmark_dataset_unavailable_reason",
    "build_csi300_index_daily_query",
    "build_sw1_index_classify_query",
    "build_sw1_index_daily_query",
    "build_sw1_index_member_all_query",
    "canonical_hash",
    "canonical_json",
    "canonicalize",
    "model_route_fingerprint",
    "persist_research_snapshot",
    "project_factors",
    "project_model_route",
    "project_structured_datasets",
    "resolve_sw1_membership",
    "safe_project_context_pack",
    "to_tushare_ts_code",
]
